---
###############################################################################
# API
###############################################################################
# Test all support REST API interactions.
#
# First apply role with all group management options defined; then run role
# again on top of this state to check group management deletions, insertions,
# and modifications.
#
# Tests:
# * Group management works correctly (new, deleted, updated groups).

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        pihole_cfg_webserver_api_pwhash: 'test'
        pihole_cfg_webserver_api_totp_secret:
          'CLAH6OEOV52XVYTKHGKBERP42IUZHY4D'
        pihole_cfg_webserver_api_app_pwhash: 'test2'
        pihole_cfg_debug_api: true
        pihole_srv_api_config_enable: true
        pihole_srv_update_enable: false
        pihole_srv_gravity_update_enable: false
platforms:
  - name: 'pihole-debian-13-api'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # services always restarted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
