---
###############################################################################
# Pi-Hole Add Clients
###############################################################################
# Clients are automatically added to the 'Default' (id=0) group in Pi-Hole upon
# creation, which apply the default blocklists. Add clients and optionally
# remove them from the 'Default' if enabled.
#
# Args:
#   client: dict (pihole_clients)
#     - id: int (unique id starting at 1)
#       ip: str (IPv4,IPv6,CIDR)
#       comment: str (user comment)
#       remove_default_group: bool (remove from automatic 'Default' group)
#
# Reference:
# * https://docs.pi-hole.net/database/

- name: 'Db | add client {{ client.id }}'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_client_insert }} ({{ client.id }}, \"{{ client.ip }}\", \"{{ client.comment }}\")"'
  become: true

- name: 'Db | remove client from default group - {{ client.id }}'
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_client_groups_delete_default }} {{ client.id }}"'
  become: true
  when: |
    'remove_default_group' in client and
    client.remove_default_group
