---
###############################################################################
# Pi-Hole DB Configuration
###############################################################################
# DB configuration is optional. DB updates are applied then gravity update is
# run to ensure database ID's are consistent. Apply before UI changes are made
# to ensure consistency.
#
# Currently, the pi-hole CLI does not manage the entire DB; if enabled, defer
# possible DB changes to the CLI.
#
# Reference:
# * https://docs.pi-hole.net/database/

- name: 'DB | include clear_databases'
  ansible.builtin.include_tasks: clear_databases.yml
  when: pihole_idempotent

- name: 'DB | add adlist source'  # noqa no-changed-when
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_ad_insert }} ({{ item.id }}, \"{{ item.address }}\", {{ item.enabled | int }}, \"{{ item.comment }}\")"'
  become: true
  loop: '{{ pihole_ad_sources }}'
  when: pihole_ad_sources|length > 0

- name: 'DB | defer to cli for domain blocklist management'
  ansible.builtin.include_tasks: cli.yml
  loop: '{{ pihole_domain_blocklists }}'
  loop_control:
    loop_var: domain
  when: pihole_use_cli and pihole_domain_blocklists|length > 0

- name: 'DB | add domain blocklist'  # noqa no-changed-when
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_domain_insert }} ({{ item.id }}, {{ item.type }}, \"{{ item.domain }}\", {{ item.enabled | int }}, \"{{ item.comment }}\")"'
  become: true
  loop: '{{ pihole_domain_blocklists }}'
  when: not pihole_use_cli and pihole_domain_blocklists|length > 0

- name: 'DB | include add_clients'
  ansible.builtin.include_tasks: add_clients.yml
  when: pihole_clients|length > 0
  loop: '{{ pihole_clients }}'
  loop_control:
    loop_var: client

- name: 'DB | add groups'  # noqa no-changed-when
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_groups_insert }} ({{ item.id }}, {{ item.enabled | int }}, \"{{ item.name }}\", \"{{ item.description }}\")"'
  become: true
  loop: '{{ pihole_groups }}'
  when: pihole_groups|length > 0

- name: 'DB | add groups ad blocklist'  # noqa no-changed-when
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_ad_groups_insert }} ({{ item.adlist_id }}, {{ item.group_id }})"'
  become: true
  loop: '{{ pihole_ad_groups_blocklist }}'
  when: pihole_ad_groups_blocklist|length > 0

- name: 'DB | add groups client blocklist'  # noqa no-changed-when
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_client_groups_insert }} ({{ item.client_id }}, {{ item.group_id }})"'
  become: true
  loop: '{{ pihole_client_groups_blocklist }}'
  when: pihole_client_groups_blocklist|length > 0

- name: 'DB | add groups domain blocklist'  # noqa no-changed-when
  ansible.builtin.command: '{{ pihole_default_sqlite3 }} "{{ pihole_default_domain_groups_insert }} ({{ item.domainlist_id }}, {{ item.group_id }})"'
  become: true
  loop: '{{ pihole_domain_groups_blocklist }}'
  when: pihole_domain_groups_blocklist|length > 0

- name: 'DB | update gravity adlists'  # noqa no-changed-when
  ansible.builtin.command: 'pihole -g'
  when: >
    not pihole_installed or
    (pihole_idempotent and not pihole_update_enable)
