---
# yamllint disable rule:line-length
###############################################################################
# Assert
###############################################################################
# Sanity check options to stop preventable errors.

- name: 'Prep | assert TOTP secret requirements'
  when: pihole_cfg_webserver_api_totp_secret | length > 0
  ansible.builtin.assert:
    quiet: true
    that:
      - pihole_cfg_webserver_api_totp_secret | length in [20, 32]
    fail_msg: |

      ✘ TOTP secret must be 20 or 32 characters.

      See pihole_cfg_webserver_api_totp_secret.

      Length: {{ pihole_cfg_webserver_api_totp_secret | length }}

- name: 'Prep | assert TOTP secret requirements'
  when: pihole_cfg_webserver_api_app_pwhash | length > 0
  ansible.builtin.assert:
    quiet: true
    that:
      - pihole_cfg_webserver_api_totp_secret | length > 0
    fail_msg: |

      ✘ Application passwords require TOTP secret.

      See pihole_cfg_webserver_api_totp_secret.

- name: 'Prep | assert REST API requirements'
  when: pihole_flg_api
  ansible.builtin.assert:
    quiet: true
    that:
      - pihole_srv_api | length > 0
      - pihole_cfg_webserver_api_pwhash | length > 0 or
        pihole_cfg_webserver_api_app_pwhash | length > 0
      - pihole_cfg_webserver_api_totp_secret | length > 0
    fail_msg: |

      ✘ Requirements not met: REST API

      REST API requires API, TOTP, and either password set:

      pihole_srv_api: {{ pihole_srv_api }}
      pihole_cfg_webserver_api_pwhash: {{ pihole_cfg_webserver_api_pwhash }}
      pihole_cfg_webserver_api_app_pwhash: {{ pihole_cfg_webserver_api_app_pwhash }}
      pihole_cfg_webserver_api_totp_secret: {{ pihole_cfg_webserver_api_totp_secret }}

- name: 'Prep | assert REST API cert validation requirements'
  when: pihole_srv_api_validate_enable
  ansible.builtin.assert:
    quiet: true
    that: pihole_cfg_webserver_tls_cert | length > 0
    fail_msg: |

      ✘ Requirements not met: certificate validation

      REST API certificate validation requires custom certificates -
      default PiHole certificates are self-signed and not valid:

      pihole_srv_api_validate_enable: {{ pihole_srv_api_validate_enable }}
      pihole_cfg_webserver_tls_cert: {{ pihole_cfg_webserver_tls_cert }}
