---
###############################################################################
# Pi-Hole dependencies.
###############################################################################
# Manage dependency installation for all platforms and VM's.

- name: 'Dependencies | debian'
  when: ansible_distribution == 'Debian'
  block:
    - name: 'Dependencies | install debian docker packages'
      ansible.builtin.apt:
        name:  '{{ pihole_default_packages_debian_docker }}'
        state: 'latest'
        update_cache: true
      when: pihole_docker

    - name: 'Dependencies | install debian packages'
      ansible.builtin.apt:
        name:  '{{ pihole_default_packages_debian }}'
        state: 'latest'
        update_cache: true
- name: 'Dependencies | ubuntu'
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: 'Dependencies | install ubuntu docker packages'
      ansible.builtin.apt:
        name:  '{{ pihole_default_packages_ubuntu_docker }}'
        state: 'latest'
        update_cache: true
      when: pihole_docker

    - name: 'Dependencies | install ubuntu packages'
      ansible.builtin.apt:
        name:  '{{ pihole_default_packages_ubuntu }}'
        state: 'latest'
        update_cache: true

- name: 'Dependencies | redhat'
  when: ansible_os_family == 'RedHat'
  block:
    - name: 'Dependencies | install redhat docker packages'
      ansible.builtin.apt:
        name:  '{{ pihole_default_packages_redhat_docker }}'
        state: 'latest'
        update_cache: true
      when: pihole_docker

    - name: 'Dependencies | install redhat packages'
      ansible.builtin.dnf:
        name:  '{{ pihole_default_packages_redhat }}'
        state: 'latest'
        update_cache: true
