---
###############################################################################
# Install
###############################################################################
# Installer automatically builds 'pihole-meta' package and must be executed in
# full bash shell.
#
# Additional configuration through REST API requires service to be running.

- name: 'Install | url | fetch latest installer'
  when: >
    not pihole__srv._installed and
    not (molecule_flg_inject | default(false))
  ansible.builtin.get_url:
    url: '{{ pihole___app._url }}'
    dest: '{{ pihole___app._basic_install }}'
    mode: 'u+rwx'
    force: false  # Only download if non-existing.
  register: pihole__download
  until: pihole__download is succeeded
  retries: 3
  delay: 2

- name: 'Install | cmd | unattended install'
  ansible.builtin.shell:
    '{{ pihole___app._basic_install ~ pihole___app._unattended_flag }}'
  args:
    executable: '/bin/bash'
    creates: '{{ pihole___app._versions }}'
  environment:
    DEBIAN_FRONTEND: 'noninteractive'
  changed_when: false

- name: 'Install | cmd | update pihole'
  when: pihole_flg_update
  ansible.builtin.shell: 'pihole -up'
  args:
    executable: '/bin/bash'
  changed_when: false

- name: 'Start | systemd | pihole-FTL'
  ansible.builtin.systemd:
    name: 'pihole-FTL.service'
    state: 'started'
    enabled: true
    daemon_reload: true
  delay: 15
  retries: 3
  register: pihole__service
  until: pihole__service.status.ActiveState == 'active'
