---
- name: 'Assert'
  ansible.builtin.include_tasks: 'assert.yml'
- name: 'Annotate'
  ansible.builtin.include_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'TOTP'
  when: _pihole_cfg_webserver_api_totp_secret.raw | length > 0
  ansible.builtin.include_tasks: 'generator/totp.yml'

- name: 'Balloon'
  ansible.builtin.include_tasks: 'generator/balloon.yml'
- name: 'Install'
  ansible.builtin.include_tasks: 'install.yml'

- name: 'API'
  when: _pihole_srv_api_config_enable.raw
  ansible.builtin.include_tasks: 'api/main.yml'

- name: 'Update'
  ansible.builtin.include_tasks: 'update.yml'
- name: 'Validate'
  ansible.builtin.include_tasks: 'validate.yml'
