---
- name: 'Assert'
  ansible.builtin.include_tasks: 'assert.yml'
- name: 'Annotate'
  ansible.builtin.include_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'TOTP'
  when: pihole_cfg_webserver_api_totp_secret | length > 0
  ansible.builtin.include_tasks: 'generator/totp.yml'

- name: 'Balloon'
  when: pihole_srv_balloon_enable
  ansible.builtin.include_tasks: 'generator/balloon.yml'

- name: 'Install'
  ansible.builtin.include_tasks: 'install.yml'

- name: 'Auth'
  when: pihole_srv_api_config_enable
  ansible.builtin.include_tasks: 'api/auth.yml'

- name: 'Validate'
  ansible.builtin.include_tasks: 'validate.yml'
