---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'Generate'
  when: pihole_flg_generate
  ansible.builtin.include_tasks: 'generate.yml'

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
- name: 'Install'
  ansible.builtin.include_tasks: 'install.yml'

- name: 'API'
  when: pihole_flg_api
  ansible.builtin.include_tasks: 'api/main.yml'

- name: 'Update | gravity'
  when: pihole_flg_gravity_update
  ansible.builtin.shell: 'pihole -g'
  args:
    executable: '/bin/bash'
  changed_when: false

- name: 'Update | post-backup'
  when: pihole_flg_api and pihole_flg_post_backup
  ansible.builtin.include_tasks: 'api/backup.yml'
  vars:
    label: 'post'

- name: 'Start'
  ansible.builtin.include_tasks: 'start.yml'
