---
###############################################################################
# API Auth
###############################################################################
# Authenticate session to PiHole REST API.

- name: 'API | auth | 2FA token'
  when: pihole__cfg._app_pwhash | length == 0
  block:
    - name: 'API | auth | ⚠ 2FA Token Required ⚠'
      ansible.builtin.debug:
        msg: |

          🗘 Enter 2FA token below (no time limit).

    - name: 'API | auth | 2FA token | read'
      ansible.builtin.pause:
        echo: true
      register: pihole__totp

    - name: 'API | auth | 2FA token | create session'
      ansible.builtin.uri:
        url: '{{ pihole__cfg._api_auth }}'
        method: 'POST'
        status_code: [200]
        body: '{
            "password": "{{ pihole__srv.pwhash }}",
            "totp": {{ pihole__totp.user_input | int }}
          }'
        body_format: 'json'
        validate_certs: '{{ pihole__cfg._api_validate }}'
      register: pihole__api

    - name: 'API | fact | cache token'
      ansible.builtin.set_fact:
        pihole__cfg: "{{ pihole__cfg | r_pufky.data.v3(

            _token=pihole__api.json.session.sid,
            _csrf=pihole__api.json.session.csrf,
          ) }}"
  rescue:
    - name: 'API | auth | ⚠ FAILED ⚠'
      ansible.builtin.fail:
        msg: |

          ✘ API Authentication failed.

          {{ pihole__api.status_code }}: {{ pihole__api.msg }}

- name: 'API | auth | create session'
  when: pihole__cfg._app_pwhash | length > 0
  block:
    - name: 'API | auth | create session'
      ansible.builtin.uri:
        url: '{{ pihole__cfg._api_auth }}'
        method: 'POST'
        status_code: [200]
        body:
          password: '{{ pihole__cfg._app_pwhash }}'
        body_format: 'json'
        validate_certs: '{{ pihole__cfg._api_validate }}'
      register: pihole__api

    - name: 'API | auth | cache tokens'
      ansible.builtin.set_fact:
        pihole__cfg: "{{ pihole__cfg | r_pufky.data.v3(

            _token=pihole__api.json.session.sid,
            _csrf=pihole__api.json.session.csrf,
          ) }}"
  rescue:
    - name: 'API | auth | ⚠ FAILED ⚠'
      ansible.builtin.fail:
        msg: |

          ✘ API Authentication failed.

          {{ pihole__api.status_code }}: {{ pihole__api.msg }}
