---
###############################################################################
# Backup
###############################################################################
# Backup completed configuration to ansible controller. Run independently of
# other API commands and must auth before attempting backup.
#
# Capture status codes for handling backup failures.
#
# Args:
#   label: str - pre/post filename label.
#
# Reference:
# * https://ftl.pi-hole.net/master/docs/#get-/teleporter

- name: 'API | backup | auth'
  ansible.builtin.include_tasks: 'api/auth.yml'

- name: 'API | backup | filename'
  ansible.builtin.set_fact:
    pihole__backup: '{{
        "/tmp/" ~ ansible_facts["date_time"].iso8601 ~ "-" ~ label ~ ".zip"
      }}'

- name: 'API | backup | run'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_teleporter }}'
    dest: '{{ pihole__backup }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
    method: 'GET'
    status_code: [200, 401]
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  register: pihole__api

- name: 'API | backup | ⚠ FAILED ⚠'
  when: pihole__api.status == 401
  ansible.builtin.fail:
    msg: |

      ✘ Backup failed.

      {{ pihole__api.msg }}

- name: '{{ "API | backup | retrieve " ~ pihole__backup }}'
  ansible.builtin.fetch:
    src: '{{ pihole__backup }}'
    dest: '{{ pihole__cfg._backup }}'
    flat: true

- name: 'API | backup | cleanup'
  ansible.builtin.file:
    path: '{{ pihole__backup }}'
    state: 'absent'
