---
###############################################################################
# API Clients
###############################################################################
# Manage PiHole clients via REST API.
#
# Determine which clients to delete from PiHole; and calculate newly added
# clients vs. pre-existing clients for updates.
#
# Reference:
# * https://ftl.pi-hole.net/master/docs/#post-/clients

- name: 'API | clients | query all'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_clients }}'
    method: 'GET'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  register: pihole__api

- name: 'API | clients | parse added, deleted clients'
  ansible.builtin.set_fact:
    pihole__clients_del: '{{
        pihole__api.json.clients | map(attribute="client") | list |
        difference(pihole__cfg._mgmt_clients | map(attribute="client") | list)
      }}'
    pihole__clients_add: '{{
        pihole__cfg._mgmt_clients | map(attribute="client") | list |
        difference(pihole__api.json.clients | map(attribute="client") | list)
      }}'

- name: 'API | clients | parse modified clients'
  ansible.builtin.set_fact:
    pihole__clients_mod: '{{
        pihole__api.json.clients | map(attribute="client") | list |
        intersect(pihole__cfg._mgmt_clients | map(attribute="client") | list) |
        reject("in", pihole__clients_add)
      }}'

- name: 'API | clients | remove non-managed client'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_clients ~ "/" ~ item | urlencode }}'
    method: 'DELETE'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [204]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  loop: '{{ pihole__clients_del }}'

- name: 'API | clients | add managed client'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_clients }}'
    method: 'POST'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [201]
    body:
      client: '{{ client.client }}'
      comment: '{{ client.comment }}'
      groups:
        '{{ client.groups | map("extract", pihole__cfg._rest_groups) | list }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    client: '{{
        pihole__cfg._mgmt_clients |
        selectattr("client", "==", item) | list | first
      }}'
  loop: '{{ pihole__clients_add }}'

- name: 'API | clients | update managed client'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_clients ~ "/" ~ client.client | urlencode }}'
    method: 'PUT'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    body:
      comment: '{{ client.comment }}'
      groups:
        '{{ client.groups | map("extract", pihole__cfg._rest_groups) | list }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    client: '{{
        pihole__cfg._mgmt_clients |
        selectattr("client", "==", item) | list | first
      }}'
  loop: '{{ pihole__clients_mod }}'
