---
###############################################################################
# API Domains
###############################################################################
# Manage PiHole domains via REST API.
#
# Domains are tracked by type, kind, domain; which makes differential tracking
# between role applications excessively complicated.
#
# Instead, query for all existing domains, remove, then create new domains
# provided by the user.
#
# Reference:
# * https://ftl.pi-hole.net/master/docs/#post-/domains/-type-/-kind-

- name: 'API | domains | query all'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_domains }}'
    method: 'GET'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  register: pihole__api

- name: 'API | domains | parse domain IDs'
  ansible.builtin.set_fact:
    pihole__domains_id: '{{ pihole__api.json.domains }}'

- name: 'API | domains | remove'
  ansible.builtin.uri:
    url: '{{
        pihole__cfg._api_domains ~ "/" ~ item.type ~ "/" ~ item.kind ~ "/" ~
        item.domain | urlencode
      }}'
    method: 'DELETE'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [204]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  loop: '{{ pihole__domains_id }}'
  loop_control:
    label: '{{ item.domain }}'

- name: 'API | domains | add managed domain'
  ansible.builtin.uri:
    url: '{{
        pihole__cfg._api_domains ~ "/" ~ item.type ~ "/" ~ item.kind |
        urlencode
      }}'
    method: 'POST'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [201]
    body:
      domain: '{{ item.domain }}'
      comment: '{{ item.comment }}'
      groups:
        '{{ item.groups | map("extract", pihole__cfg._rest_groups) | list }}'
      enabled: '{{ item.enabled }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  loop: '{{ pihole__cfg._mgmt_domains }}'
  loop_control:
    label: '{{ item.domain }}'
