---
###############################################################################
# API Groups
###############################################################################
# Manage PiHole groups via REST API.
#
# Determine which groups to delete from PiHole; and calculate newly added
# groups vs. pre-existing groups for updates.
#
# Once all modifications are done, query final group state for further API
# processing.
#
# Reference:
# * https://ftl.pi-hole.net/master/docs/#post-/groups

- name: 'API | groups | query all'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_groups }}'
    method: 'GET'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  register: pihole__api

- name: 'API | groups | parse added, deleted groups'
  ansible.builtin.set_fact:
    pihole__groups_del: '{{
        pihole__api.json.groups | map(attribute="name") | list |
        difference(pihole__cfg._mgmt_groups | map(attribute="name") | list)
      }}'
    pihole__groups_add: '{{
        pihole__cfg._mgmt_groups | map(attribute="name") | list |
        difference(pihole__api.json.groups | map(attribute="name") | list)
      }}'

- name: 'API | groups | parse modified groups'
  ansible.builtin.set_fact:
    pihole__groups_mod: '{{
        pihole__api.json.groups | map(attribute="name") | list |
        intersect(pihole__cfg._mgmt_groups | map(attribute="name") | list) |
        reject("in", pihole__groups_add)
      }}'

- name: 'API | groups | remove non-managed group'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_groups ~ "/" ~ item | urlencode }}'
    method: 'DELETE'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [204]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  loop: '{{ pihole__groups_del }}'

- name: 'API | groups | add managed group'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_groups }}'
    method: 'POST'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [201]
    body:
      name: '{{ group.name }}'
      comment: '{{ group.comment }}'
      enabled: '{{ group.enabled }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    group: '{{
        pihole__cfg._mgmt_groups |
        selectattr("name", "==", item) | list | first
      }}'
  loop: '{{ pihole__groups_add }}'

- name: 'API | groups | update managed group'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_groups ~ "/" ~ group.name | urlencode }}'
    method: 'PUT'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    body:
      name: '{{ group.name }}'
      comment: '{{ group.comment }}'
      enabled: '{{ group.enabled }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    group: '{{
        pihole__cfg._mgmt_groups |
        selectattr("name", "==", item) | list | first
      }}'
  loop: '{{ pihole__groups_mod }}'

- name: 'API | groups | query final group state'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_groups }}'
    method: 'GET'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  register: pihole__api

- name: 'API | groups | cache group mapping'
  ansible.builtin.set_fact:
    pihole__cfg: "{{ pihole__cfg | r_pufky.data.v3(

        _rest_groups=(
          pihole__api.json.groups |
          items2dict(key_name='name', value_name='id')
        ),
      ) }}"
