---
###############################################################################
# API Lists
###############################################################################
# Manage PiHole lists via REST API.
#
# Determine which lists to delete from PiHole; and calculate newly added
# lists vs. pre-existing lists for updates. Existing lists types are required
# to correctly query API for updates.
#
# Reference:
# * https://ftl.pi-hole.net/master/docs/#post-/lists

- name: 'API | lists | query all'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_lists }}'
    method: 'GET'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    validate_certs: '{{ pihole__cfg._api_validate }}'
  register: pihole__api

- name: 'API | domains | parse lists'
  ansible.builtin.set_fact:
    pihole__lists: '{{ pihole__api.json.lists }}'

- name: 'API | lists | parse existing lists'
  ansible.builtin.set_fact:
    pihole__lists_del: '{{
        pihole__lists | map(attribute="address") | list |
        difference(pihole__cfg._mgmt_lists | map(attribute="address") | list)
      }}'
    pihole__lists_add: '{{
        pihole__cfg._mgmt_lists | map(attribute="address") | list |
        difference(pihole__lists | map(attribute="address") | list)
      }}'

- name: 'API | lists | parse modified lists'
  ansible.builtin.set_fact:
    pihole__lists_mod: '{{
        pihole__lists | map(attribute="address") | list |
        intersect(pihole__cfg._mgmt_lists | map(attribute="address") | list) |
        reject("in", pihole__lists_add)
      }}'

- name: 'API | lists | remove non-managed list'
  ansible.builtin.uri:
    url: '{{
        pihole__cfg._api_lists ~ "/" ~
        (list.address | urlencode | regex_replace("/", "%2F")) ~
        "?type=" ~ list.type
      }}'
    method: 'DELETE'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [204]
    body:
      sid: '{{ pihole__cfg._token }}'
      csrf: '{{ pihole__cfg._csrf }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    list:
      '{{ pihole__lists | selectattr("address", "==", item) | list | first }}'
  loop: '{{ pihole__lists_del }}'

- name: 'API | lists | add managed list'
  ansible.builtin.uri:
    url: '{{ pihole__cfg._api_lists ~ "?type=" ~ list.type }}'
    method: 'POST'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [201]
    body:
      address: '{{ list.address }}'
      type: '{{ list.type }}'
      comment: '{{ list.comment }}'
      groups:
        '{{ list.groups | map("extract", pihole__cfg._rest_groups) | list }}'
      enabled: '{{ list.enabled }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    list: '{{
        pihole__cfg._mgmt_lists |
        selectattr("address", "==", item) | list | first
      }}'
  loop: '{{ pihole__lists_add }}'

- name: 'API | lists | update managed list'
  ansible.builtin.uri:
    url: '{{
        pihole__cfg._api_lists ~ "/" ~
        (current.address | urlencode | regex_replace("/", "%2F")) ~
        "?type=" ~ current.type
      }}'
    method: 'PUT'
    headers:
      X-FTL-SID: '{{ pihole__cfg._token }}'
      X-CSRF-TOKEN: '{{ pihole__cfg._csrf }}'
    status_code: [200]
    body:
      comment: '{{ update.comment }}'
      type: '{{ update.type }}'
      groups:
        '{{ update.groups | map("extract", pihole__cfg._rest_groups) | list }}'
      enabled: '{{ update.enabled }}'
    body_format: 'json'
    validate_certs: '{{ pihole__cfg._api_validate }}'
  vars:
    current: '{{
        pihole__lists | selectattr("address", "==", item) | list | first
      }}'
    update: '{{
        pihole__cfg._mgmt_lists |
        selectattr("address", "==", item) | list | first
      }}'
  loop: '{{ pihole__lists_mod }}'
