---
- name: 'Converge'
  hosts: 'all'
  gather_facts: true  # ansible_facts['date_time'].
  tasks:
    - name: 'Converge | roles | r_pufky.srv.pihole (backup)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.pihole'
