---
- name: 'Verify'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Verify | filesystem | query backups'
      ansible.builtin.find:
        path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/backup"
          }}'
        file_type: 'file'
      register: pihole__test

    - name: 'Verify | assert | backups'
      ansible.builtin.assert:
        quiet: true
        that: pihole__test.files | length >= 2
        fail_msg: |

          ✘ Backup count invalid.

          There should only be at least 1 pre and post backup.

          Count: {{ pihole__test.files | length }}
          Files: {{ pihole__test.files | map(attribute='path') | list }}
