---
###############################################################################
# Feature Flags
###############################################################################

# 1. Generate TOTP, password hashes?
#
# Generates totp_secret, pwhash, app_pwhash then exits. Generated hashes should
# be added to sourced pihole.toml using vault. See pihole_cfg_*.
#
# Default: False.
pihole_flg_generate: false

# 2. Run backup before applying role changes? Default: False.
pihole_flg_pre_backup: false

# 3. Apply PiHole updates?
#
# Updates are applied immediately after installation before configuration.
#
# Default: True.
#
# Reference:
# * https://docs.pi-hole.net/main/update
pihole_flg_update: true

# 4. Perform additional configuration via REST API?
#
# Applies pihole_cfg_mgmt_* via REST API. pihole_srv_api must be set. Disabling
# will skip all tasks which require REST API use.
#
# Default: False.
pihole_flg_api: false

# 5. Apply Gravity updates?
#
# pihole_cfg_mgmt_* changes require gravity updates to be populated. Run after
# all configuration is complete.
#
# Default: True.
#
# Reference:
# * https://docs.pi-hole.net/main/update
pihole_flg_gravity_update: true

# 5. Run backup after applying role changes? Default: False.
pihole_flg_post_backup: false

###############################################################################
# Service
###############################################################################

# Create restricted PiHole user?
#
# Install a modified pihole user with additional restrictions.
#
# Changes:
# * UID: 123 (default: 997).
# * GID: 123 (default: auto).
# * home: /nonexistent (default: /home/pihole).
#
# Default: True.
pihole_srv_restrict: true

# PiHole pihole.toml to set.
#
# Ansible controller path to source pihole.toml (treated as a jinja2 template
# allowing for ansible variable interpretation). Overwrites existing
# /etc/pihole/pihole.toml. PiHole will rewrite this file on startup with
# comments, resulting in an 'always changed' status if the provided file does
# not strictly follow the re-write format.
#
# A default configuration is autogenerated if not provided (see
# templates/default).
#
# pihole_srv_cfg: 'host_vars/pihole.example.com/pihole.toml'
#
# Default: '' (use minimally configured default).
pihole_srv_cfg: ''

# PiHole conf.d directory to set.
#
# Ansible controller path to source conf.d files (treated as a jinja2 templates
# allowing for ansible variable interpretation). Overwrites existing config
# data in /etc/pihole/conf.d/*. Custom certificates, etc. should be included
# here and sourced in pihole.toml as needed. PiHole manages file permissions.
# Files not sourced will be removed.
#
# pihole_srv_conf_d: 'host_vars/pihole.example.com/conf.d'
#
# Default: '' (disabled).
pihole_srv_conf_d: ''

# Stop PiHole during configuration?
#
# In certain virtualization cases pre-existing PiHole installations may not
# pickup config file changes and require the service to be restarted.
#
# Enabling WILL cause service interruption.
#
# Default: False.
pihole_srv_restart: false

###############################################################################
# Config
###############################################################################

# PiHole API endpoint to use for service configuration.
#
# Default: 'https://localhost:443/api'
pihole_cfg_api: 'https://localhost:443/api'

# Enable API certificate validation?
#
# PiHole generates self-signed TLS/SSL certificates which does not validate. A
# custom TLS/SSL certificate must be deployed via pihole_srv_conf_d and set
# in pihole.toml.
#
# Default: False.
pihole_cfg_api_validate: false

# Ansible controller backup save location.
#
# Backups are provided via REST API through Teleporter and retrieved. Relative
# paths are anchored to playbook.
#
# Default: 'group_vars/pihole/data'.
pihole_cfg_backup: 'group_vars/pihole/data'

# Webserver (pwhash) password to hash.
#
# Default: '{RANDOM}' (randomly generated).
pihole_cfg_pwhash: '{{
    lookup("ansible.builtin.password",
           "/dev/null",
           chars=["ascii_lowercase", "ascii_uppercase", "digits"],
           length=32)
  }}'

# REST API application (app_pwhash) password to hash.
#
# REST API uses this password to execute operations.
#
# Special Case:
# * API calls will prompt for 2FA token if needed when no application password
#   is set.
# * pihole.toml is not read for app_pwhash as it is hashed.
# * PiHole creates a 44 character app password - this is not a hard limit.
#
# Default: '{RANDOM}' (randomly generated).
pihole_cfg_app_pwhash: '{{
    lookup("ansible.builtin.password",
           "/dev/null",
           chars=["ascii_lowercase", "ascii_uppercase", "digits"],
           length=44)
  }}'

###############################################################################
# Group Management Lists
###############################################################################
# Group Management lists are configured via REST API. Application password used
# with fallback to web password with TOTP token prompt.

# Group Management ➔ Groups.
#
# Special Case:
# * Default (id:0) is automatically created on installation; however this
#   should **always** be specified to make role applications idempotent.
# * Each newly added client or domain gets assigned to group id:0 when being
#   added.
#
# pihole_cfg_mgmt_groups:
#       list of dict - Group definitions.
#   - name: str - Group name.
#     comment: str - Group description.
#     enabled: bool - Enable processing of objects linked to this group.
#
# default:
#   - name: 'Default'
#     comment: 'The default group'
#     enable: true
pihole_cfg_mgmt_groups:
  - name: 'Default'
    comment: 'The default group'
    enabled: true

# Group Management ➔ Clients
#
# pihole_cfg_mgmt_clients:
#     list of dict - Client definitions.
#   - client: str - Client identifier (IPv4, IPv6, CIDR, MAC, Hostname, or
#         Interface). IP/CIDR preferred over MAC/Hostname/Interface as the
#         latter will only be available after some time. MAC recognition only
#         works for devices at most one networking hop away.
#         Special Case:
#           ^:{INTERFACE}: Interfaces must be pre-pended with colon ':'.
#     comment: str - Client description.
#     groups: list of str - Groups client belongs to. Use
#         pihole_cfg_mgmt_groups[].name.
#
# pihole_cfg_mgmt_clients:
#   - client: '00:11:22:AA:BB:CC'
#     comment: 'lappy'
#     groups:
#       - 'Default'
#       - 'laptops'
#
# Default: [].
pihole_cfg_mgmt_clients: []

# Group Management ➔ Domains
#
# pihole_cfg_mgmt_domains:
#     list of dict - Domain definitions.
#   - domain: str - Domain or regex pattern. Unicode characters accepted.
#     type: str - Domain type.
#         Values:
#           allow: Allow domain.
#           deny: Deny domain.
#     kind: str - Domain matching method (kind).
#         Values:
#           exact: Exact domain string match.
#           regex: Regex domain string match.
#     comment: str - Domain description.
#     groups: list of str - Groups client belongs to. Use
#         pihole_cfg_mgmt_groups[].name.
#     enabled: bool - Enable domain rule.
#
# pihole_cfg_mgmt_domains:
#   - domain: 'example.com'
#     type: 'allow'
#     kind: 'exact'
#     comment: 'Example allowed domain match.'
#     groups: ['Default']
#     enabled: true
#
# Default: [].
pihole_cfg_mgmt_domains: []

# Group Management ➔ Lists
#
# pihole_cfg_mgmt_lists:
#     list of dict - Subscribed list definitions.
#   - address: str - List URL.
#     type: str - List type.
#         Values:
#           allow: Allow domains on list.
#           block: Block domains on list.
#     comment: str - Domain description.
#     groups: list of str - Groups client belongs to. Use
#         pihole_cfg_mgmt_groups[].name.
#     enabled: bool - Enable domain rule.
#
# Default:
#   - address:
#       'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
#     type: 'block'
#     comment: 'Migrated from /etc/pihole/adlists.list'
#     groups: ['Default']
#     enabled: true
pihole_cfg_mgmt_lists:
  - address: 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
    type: 'block'
    comment: 'Migrated from /etc/pihole/adlists.list'
    groups: ['Default']
    enabled: true
