---
###############################################################################
# Default
###############################################################################
# Default options start service correctly, with REST API login validated.
#
# Tests:
# * All default options (unset defaults set with options) set.
# * Example conf.d is deployed with no runtime errors.
# * /etc/pihole/pihole.toml.broken does NOT exist (verified in start.yml).

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        molecule_flg_inject: true
        pihole_srv_conf_d: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/conf.d"
          }}'
platforms:
  - name: 'pihole-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '1080:80/tcp'
      - '1443:443/tcp'
      - '8080:8080/tcp'
      - '8443:8443/tcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
