---
###############################################################################
# Default
###############################################################################
# Default options start service correctly, with REST API login validated.
#
# Tests:
# * All default options (unset defaults set with options) set.
# * Raw web password works with balloon hashing.
# * Raw app password works with balloon hashing.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        pihole_cfg_webserver_api_pwhash: 'test'
        pihole_cfg_webserver_api_totp_secret:
          'CLAH6OEOV52XVYTKHGKBERP42IUZHY4D'
        pihole_cfg_webserver_api_app_pwhash: 'test2'
        pihole_cfg_debug_api: true
        pihole_srv_api_config_enable: true
platforms:
  - name: 'pihole-debian-13-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '1080:80/tcp'
      - '1443:443/tcp'
      - '8080:8080/tcp'
      - '8443:8443/tcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
