---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | cache'

    - name: 'Prepare | fact | generate conf.d cache location'
      ansible.builtin.set_fact:
        pihole__cache: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/conf.d"
          }}'

    - name: '{{ "Prepare | filesystem | create " ~ pihole__cache }}'
      ansible.builtin.file:
        path: '{{ pihole__cache }}'
        mode: '0755'
        state: 'directory'

    - name:
        '{{ "Prepare | cache | " ~ pihole___app._basic_install | basename }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{ "Prepare | cache | " ~ pihole___app._basic_install | basename }}'
        test_dest: '{{ pihole___app._basic_install | basename }}'
        test_url: '{{ pihole___app._url }}'
        test_mode: '0640'

    - name: 'Prepare | cache | balloon source'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_git.yml'
      vars:
        test_name: 'Prepare | cache | balloon source'
        test_dest: 'balloon'
        test_repo: '{{ pihole___balloon._url }}'

    - name: 'Prepare | cache | cleanup balloon source'
      ansible.builtin.file:
        path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/balloon/" ~ item
          }}'
        state: 'absent'
      loop:
        - '.coveragerc'
        - '.git'
        - '.github'
        - '.gitignore'

    - name: 'Prepare | cmd | generate RSA private key'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'genrsa'
          - '-out'
          - '{{ pihole__cache ~ "/pihole_test.key" }}'
          - '2048'
        creates: '{{ pihole__cache ~ "/pihole_test.key" }}'

    - name: 'Prepare | cmd | generate certificate signing request CSR'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'req'
          - '-new'
          - '-key'
          - '{{ pihole__cache ~ "/pihole_test.key" }}'
          - '-out'
          - '{{ pihole__cache ~ "/pihole_test.csr" }}'
          - '-subj'
          - '/CN=127.0.01'
        creates: '{{ pihole__cache ~ "/pihole_test.csr" }}'

    - name: 'Prepare | cmd | create self-signed certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'x509'
          - '-req'
          - '-days'
          - '3600'
          - '-in'
          - '{{ pihole__cache ~ "/pihole_test.csr" }}'
          - '-signkey'
          - '{{ pihole__cache ~ "/pihole_test.key" }}'
          - '-out'
          - '{{ pihole__cache ~ "/pihole_test.crt" }}'
        creates: '{{ pihole__cache ~ "/pihole_test.crt" }}'

    - name: 'Prepare | cmd | generate pihole_test.pem'
      ansible.builtin.shell: >
        cat
        {{ pihole__cache ~ "/pihole_test.crt " }}
        {{ pihole__cache ~ "/pihole_test.key > " }}
        {{ pihole__cache ~ "/pihole_test.pem" }}
      args:
        creates: '{{ pihole__cache ~ "/pihole_test.pem" }}'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | inject | required testing packages'
      ansible.builtin.apt:
        name: 'rsync'
        state: 'present'

    - name: 'Prepare | stage basic-install.sh'
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/basic-install.sh"
          }}'
        dest: '/tmp/basic-install.sh'
        owner: 'root'
        group: 'root'
        mode: '0755'
        directory_mode: '0755'
        force: false

    - name: 'Prepare | stage balloon'
      ansible.posix.synchronize:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/balloon/"
          }}'
        dest: '/opt/balloon-hashing'
        delete: true
        recursive: true
        archive: false
        checksum: true
